server:
  port: 8081

spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/user_service
  username: bkokkili
  password: June@1520
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

address-service:
  base-url: http://localhost:8082

management:
  tracing:
    sampling:
      probability: 1.0